networks:
  dev_network:
    driver: bridge

services:
  fastapi-app:
    build: .                          # Собирать образ из Dockerfile в этой же папке
    container_name: fastapi_dev
    restart: always
    ports:
      - "8000:8000"                   # Пробрасываем порт 8000 наружу на плату
    volumes:
      - .:/app                        # Монтируем текущую папку, чтобы изменения в коде подтягивались на лету
